version: '3.0'

services:
  client-cl:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_cl_balanced
    privileged: true
    ports:
      - "8080:8080"
    environment:
      - CL_SERVER_ADDRESS=http://${SERVER_IP}:8080
      - PYTHONUNBUFFERED=1
      - HOSTNAME=${CLIENT_ID}
      - CAMERA_INDEX=0
      - CAMERA_FORMAT=MJPG
      - CAMERA_WIDTH=1280
      - CAMERA_HEIGHT=720
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - cl-client-data:/app/data
      - ${RAW_DATA_PATH_CLIENT}:/app/raw_data/students
    networks:
      - cl-network

networks:
  cl-network:
    driver: bridge

volumes:
  cl-client-data:
