services:
  server-cl:
    build: ./server
    container_name: centralized_server
    ports:
      - "8081:8080"
    environment:
      DATABASE_URL: postgresql://admin:admin123@server-cl-db:5432/cl_server
      PYTHONUNBUFFERED: 1
    depends_on:
      server-cl-db:
        condition: service_healthy

  server-cl-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=cl_server
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d cl_server" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - server_cl_data:/var/lib/postgresql/data

volumes:
  server_cl_data:
