services:
  # --- SERVER PUSAT (CENTRALIZED) ---
  server-cl:
    build: ./server
    container_name: centralized_server
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      DATABASE_URL: postgresql://admin:admin123@server-cl-db:5432/cl_server
      PYTHONUNBUFFERED: 1
    depends_on:
      server-cl-db:
        condition: service_healthy
    volumes:
      - cl-server:/app/data
    networks:
      - clnet

  # --- TERMINAL CLIENT 1 ---
  client1-cl:
    build: ./client
    container_name: centralized_client1
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      CL_SERVER_ADDRESS: http://server-cl:8080
      PYTHONUNBUFFERED: 1
    volumes:
      - ../datasets/client1_data:/app/raw_data
      - cl-client-1:/app/data
    networks:
      - clnet

  # --- TERMINAL CLIENT 2 ---
  client2-cl:
    build: ./client
    container_name: centralized_client2
    restart: unless-stopped
    ports:
      - "8083:8080"
    environment:
      CL_SERVER_ADDRESS: http://server-cl:8080
      PYTHONUNBUFFERED: 1
    volumes:
      - ../datasets/client2_data:/app/raw_data
      - cl-client-2:/app/data
    networks:
      - clnet

  # --- DATABASE SERVER ---
  server-cl-db:
    image: postgres:15-alpine
    restart: unless-stopped
    command: postgres -c shared_buffers=64MB -c max_connections=50 -c work_mem=8MB
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=cl_server
    ports:
      - "5432:5432"
    volumes:
      - cl-db:/var/lib/postgresql/data
    networks:
      - clnet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d cl_server" ]
      interval: 5s
      timeout: 5s
      retries: 5
  # --- DATABASE CLIENT 1 ---

networks:
  clnet:
    driver: bridge

volumes:
  cl-server:
  cl-db:
  cl-client-1:
  cl-client-2:
