services:
  server-fl:
    build:
      context: ../../../federated-learning
      dockerfile: server/Dockerfile
    container_name: server_fl_extreme
    ports:
      - "8081:8080"
      - "8085:8085"
    environment:
      - DATABASE_URL=postgresql://server:server123@server-fl-db-extreme:5432/fl_server
      - PYTHONUNBUFFERED=1
    depends_on:
      server-fl-db-extreme:
        condition: service_healthy
    volumes:
      - ./data:/app/data
    networks:
      - fl-network

  server-fl-db-extreme:
    image: postgres:15
    container_name: db_server_fl_extreme
    environment:
      - POSTGRES_USER=server
      - POSTGRES_PASSWORD=server123
      - POSTGRES_DB=fl_server
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U server -d fl_server" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - fl-network

networks:
  fl-network:
    driver: bridge
