version: '3.0'

services:
  client-fl:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_fl_balanced
    privileged: true
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=sqlite:////app/data/client.db
      - SERVER_API_URL=http://${SERVER_IP}:8080
      - FL_SERVER_ADDRESS=${SERVER_IP}:8085
      - PYTHONUNBUFFERED=1
      - HOSTNAME=${CLIENT_ID}
      - CLIENT_PORT=8080
      - CAMERA_INDEX=0
      - CAMERA_FORMAT=MJPG
      - CAMERA_WIDTH=1280
      - CAMERA_HEIGHT=720
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - ./client/data:/app/data
      - ${RAW_DATA_PATH_CLIENT}:/app/raw_data
    networks:
      - fl-network

networks:
  fl-network:
    driver: bridge
