services:
  client2-fl:
    build: ./client
    container_name: federated_client2
    ports:
      - "8083:8080"
    environment:
      DATABASE_URL: postgresql://client:client123@client2-fl-db:5432/fl_client
      SERVER_API_URL: http://${SERVER_IP}:8081
      FL_SERVER_ADDRESS: ${SERVER_IP}:8085
      PYTHONUNBUFFERED: 1
      HOSTNAME: terminal-2
    depends_on:
      client2-fl-db:
        condition: service_healthy
    volumes:
      - ./${RAW_DATA_PATH_CLIENT2}:/app/raw_data

  client2-fl-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=client
      - POSTGRES_PASSWORD=client123
      - POSTGRES_DB=fl_client
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U client -d fl_client" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - client2_fl_data:/var/lib/postgresql/data

volumes:
  client2_fl_data:
