services:
  # --- SERVER FEDERATED (AGGREGATOR) ---
  server-fl:
    build: ./server
    container_name: federated_server
    restart: unless-stopped
    ports:
      - "8081:8080"
      - "8085:8085"
    environment:
      DATABASE_URL: postgresql://admin:admin123@server-fl-db:5432/fl_server
      PYTHONUNBUFFERED: 1
    depends_on:
      server-fl-db:
        condition: service_healthy
    volumes:
      - fl-server:/app/data
    networks:
      - flnet

  # --- TERMINAL CLIENT 1 ---
  client1-fl:
    build: ./client
    container_name: federated_client1
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      DATABASE_URL: sqlite:////app/data/client.db
      SERVER_API_URL: http://server-fl:8080
      FL_SERVER_ADDRESS: server-fl:8085
      PYTHONUNBUFFERED: 1
    volumes:
      - ../datasets/client1_data:/app/raw_data
      - fl-client-1:/app/data
    networks:
      - flnet

  # --- TERMINAL CLIENT 2 ---
  client2-fl:
    build: ./client
    container_name: federated_client2
    restart: unless-stopped
    ports:
      - "8083:8080"
    environment:
      DATABASE_URL: sqlite:////app/data/client.db
      SERVER_API_URL: http://server-fl:8080
      FL_SERVER_ADDRESS: server-fl:8085
      PYTHONUNBUFFERED: 1
    volumes:
      - ../datasets/client2_data:/app/raw_data
      - fl-client-2:/app/data
    networks:
      - flnet

  # --- DATABASE SERVER ---
  server-fl-db:
    image: postgres:15-alpine
    restart: unless-stopped
    command: postgres -c shared_buffers=64MB -c max_connections=50 -c work_mem=8MB
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=fl_server
    ports:
      - "5432:5432"
    volumes:
      - fl-db:/var/lib/postgresql/data
    networks:
      - flnet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d fl_server" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  flnet:
    driver: bridge

volumes:
  fl-server:
  fl-db:
  fl-client-1:
  fl-client-2:
