version: '3.0'

services:
  server-fl:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server_fl_balanced
    ports:
      - "8080:8080"
      - "8085:8085"
    environment:
      - DATABASE_URL=postgresql://server:server123@server-fl-db-balanced:5432/fl_server
      - PYTHONUNBUFFERED=1
    depends_on:
      server-fl-db-balanced:
        condition: service_healthy
    volumes:
      - fl-server:/app/data
    networks:
      - fl-network

  server-fl-db-balanced:
    image: postgres:15
    container_name: db_server_fl_balanced
    environment:
      - POSTGRES_USER=server
      - POSTGRES_PASSWORD=server123
      - POSTGRES_DB=fl_server
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U server -d fl_server" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - fl-db:/var/lib/postgresql/data
    networks:
      - fl-network

networks:
  fl-network:
    driver: bridge

volumes:
  fl-server:
  fl-db: